[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "picotool load -u -v -x -t elf"
runner = "probe-rs run --chip RP235x --protocol swd --speed 16000"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
# pick one of the following options by uncommenting it
# runner = "picotool load -u -v -x -t elf"
